#!/bin/bash

dir=$(dirname "$0")

cd "$dir" || exit 1

echo "==> openssl"
./openssl.sh

echo
echo "==> Go"
go test -v ./go_test.go

echo
echo "==> Perl"
prove -v ./perl.t

echo
echo "==> Node"
/node_modules/.bin/jest

echo
echo "==> Node (NODE_EXTRA_CA_CERTS)"
NODE_EXTRA_CA_CERTS=/opt/intermediate-certs/ca-bundle.crt /node_modules/.bin/jest
